<!DOCTYPE html>
<html>
	<?php include_once "header.php";?>
	
	  	<div id="content">
	  		<div id="accordion">
	  			<h2>Research fellow/assistant in EECS dept, UCI</h2>
	  			<div class="inner">
	  				I was a research fellow/assistant in EECS dept, UCI from winter 2010 to present. My research topics can be found in the
	  				<a href="">Research</a> section of this webpage.
	  			</div>
			    <h2>Teaching assistant for C programming language (EECS 10) in EECS, UCI</h2>
			    <div class="inner">
					I was teaching assistant for C programming language (course code :EECS 10) during summer 2011.
					<h4>Responsibilities</h4>
					<ol>
						<li>Designed problems for laboratory session to help the students to understand the basic syntax and the 
							programing methodology in C language.</li>
						<li>Instructed the discussion session to teach the basics in C language and anaswered any questions raised
							by the students. </li>
						<li>Taught the student how to think in "the computer way".</li>
						<li>Students loved me a lot.</li>
					</ol>
				</div>
			    <h2>Teaching assistant for Electronic Circuit lab (EECS 170AL) in EECS, UCI</h2>
			    <div class="inner">
					I was teaching assistant for the electronics circuit lab (course code: EECS 170AL) during fall 2010.
					<h4>Responsibilities</h4>
					<ol>
						<li>Designed laboratory experiments for basic semiconductor devices including different types of diodes, 
							bipolar transistors, CMOS transistor and various circuits topologies.</li>
						<li>Instructed and conducted the laboratory session. Taught the students how to build eletronic circuits based
							on the components given and helped them to debug the circuits.</li>
						<li>Instructed basic principles of various semiconductor devices.</li>
					</ol>
				</div>
				<h2>Summer internship in Broadcom Corporation, Irvine, CA</h2>
				<div class="inner">
					I was summer intern in RF DVT group, Broadcom from 07/2009 to 09/2009. My group manager was Long Tran. 
					During this 3 months, I worked with other engineers in the team on various different aspects of engineer jobs. 
					I learnt a lot from all my engineering mentors. One of my engineering mentor said that I was the best intern he
					had.
					<h4>Highlights</h4>
					<ol>
						<li>Got familiar with WLAN transceiver architecture and various building blocks. Deepened understanding
							on various design specifications and how to test them.</li>
						<li>Conducted manual/automated testing and debugging of different WLAN SISO/MIMO chipsets. Learned the
							methodology of different testing and measurements, including power, gain, TSSI, RSSI, IM1dB, IP3, 
							Phase Noise, Spur emission, Tx/Rx tuning, VCO tuning, source/load pulling IQ calibration, Tx EVM and spectral mask, 
							Rx BER and sensitivity.</li>
						<li>Devoloped automated WLAN chip testing programs using Python and Tcl.</li>
						<li>Developed and commited an automated testing report generation and uploading system using Python
							and Latex. After testing result plots were generated using Pyplot module, a Latex file was generated
							using Python script to compile the results. The PDF files was then generated by invoking the 
							pdftk tools from Python using the os module. The files were finally uploaded to the wiki server for
							publishing. </li>
						<li>Learned how to implement test automation with IEEE 488 standard thru GPIB</li>
						<li>Learned JTAG debugging and IEEE 1149 boundary scan development and testing </li>
						<li>Configured the networking and development environment for three test linux boxes.</li>
					</ol>
				</div>
				<h2>Summer internship in Zhongxing Telecom. Equipment Ltd.(ZTE), Beijing</h2>
				<div class="inner">
					I was a summer intern in ZTE from 08/2008 to 09/2008. During this one month,
					I learned the basic principles of GSM, CDMA, SDH and SONET as well as how to configure
					optical and communication networks and wirelesss base-stations.
				</div>
	  		</div>  <!-- end of accordion -->
	  	</div>  <!-- end of content -->
	  		  		
	<?php include_once "footer.php" ?>

</html>